### PR TITLE
OXT-389: use a bigger RSA certificate to match the bigger key

### PR DESCRIPTION
**Pull request by jean-edouard**
Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by pearsonk** [comment]
+1 from looking at the diff. Tested the approach independently (encryption of 512b with 8192b RSA key) and does not throw the "data too large for key size" error.

**Comment by cjp256** [comment]
LGTM

**Comment by rossphilipson** [comment]
Giving this a try with this build: http://openxt.ainfosec.com:8020/builders/extbuilder/builds/321

**Comment by rossphilipson** [comment]
Tested. Looks good. Notes on testing in the ticket. Will merge in a while.

**Pull request merged**
