### PR TITLE
Delay wiping MBR until after Ready-to-install.

### PR DESCRIPTION
**Pull request by troyc**
OXT-1052

Signed-off-by: Troy Crosley <crosleyt@ainfosec.com>

### CODE REVIEW

**Comment by jean-edouard** [comment]
Built here: http://openxt-builder.ainfosec.com:8010/builders/openxt/builds/948

**Comment by jean-edouard** [comment]
There's an early "WARNING" screen which says that all data will be erased, which doesn't happen right away anymore. And then the dialog preceding the actual data removal just says "Proceed with installation?".
Maybe the warning should be moved/copied from the first dialog to the second?

Otherwise, this works as expected, aborting at the last minute doesn't break any previous installation.

**Comment by jean-edouard** [comment]
@troyc, see comment above

**Comment by troyc** [comment]
The user is warned that data will be erased after selecting the hard drive to use (note that the user isn't asked to select the hard drive if there's only one), which is followed by asking for the recovery password and whether to use measured launch. This is the same order as in OpenXT 6.0.0. Do you think it would be better if hard drive selection and warning were the last steps before being asked to proceed with installation?

**Comment by jean-edouard** [comment]
@troyc, I don't know, it just seemed weird to see the warning long before the erase actually happens, I thought it was worth mentioning.
I'm fine merging this if you think it's good like that.

**Comment by troyc** [comment]
I don't feel compelled to make any change since it's such a minor concern and due for a rework anyways (to add GPT support and possibly the ability to preserve existing partitions).

**Comment by jean-edouard** [comment]
Makes sense. @dpsmith, want this in stable-7?

**Comment by dpsmith** [comment]
Yes, but I since its minor, think it should go in RC2 unless there is a reason to get it in now.

**Comment by jean-edouard** [comment]
Ok, I'll let you keep track of that, merging soon.

**Comment by dpsmith** [comment]
A stable-7 version PR can be made and just not merged until after RC1 tag.

**Comment by jean-edouard** [comment]
Ack, @troyc, see above, please PR a cherry-pick for stable-7.

**Pull request merged**
