### PR TITLE
Dynamically create dom0 rootfs lv size.

### PR DESCRIPTION
**Pull request by crogers1**
Signed-off-by: Chris Rogers <rogersc@ainfosec.com>

### CODE REVIEW

**Comment by crogers1** [comment]
This PR is related to https://github.com/OpenXT/openxt/pull/72.

I would like some feedback on this approach to dynamically setting the dom0 size.  Currently, we hardcode the size we want for dom0 and as components are added/removed over time, it requires someone to manually make the change.  This is not ideal, therefore we should determine the size dynamically.

**Comment by jean-edouard** [comment]
- There's a pushd without a popd, is that expected?
- Minor indent issue
- About the math for calculating the size, it gets rounded up to the closest multiple of 40, which is not very consistent, as for example a 339MB image will get only 1MB of free space, and a 301MB image will get 39MB.

**Comment by crogers1** [comment]
Yep, I realized the pushd is actually unecessary, will fix indent and come up with something better for the size calculation.  Thanks.

**Comment by jean-edouard** [comment]
That looks good.
For getting the uncompressed size, I would have used something slightly more reliable like:
gzip -l ${DOM0_ROOTFS} | tail -1 | awk '{print $2}'
or the slower but 100% reliable:
zcat ${DOM0_ROOTFS} | wc -c
but you're approach seems to work.

+1

**Comment by jean-edouard** [comment]
I built this last night and tested it today.
The patch works as expected, so I still +1.

However, I discovered that the sizing is quite wrong, with or without this PR.
If you take dom0 from last night's build, `gzip -l` will give you and uncompressed size of 363566080.
$(( 363566080 / 1048576 )) == 346[MB]
After adding 10%, we're at 380MB.
However, after installing that build, I get a dom0 partition of 328MB (instead of 380), with a used space of 252MB (instead of 346!). The logical volume has the expected size of 380MB.
Then after running `resize2fs /dev/mapper/xenclient-root`, the dom0 partition get bumped to 361MB...

**Comment by crogers1** [comment]
Updated PR, all we need to do is set the LV size to the uncompressed dom0-rootfs size, no padding or anything.  Changed to use zcat since it provides the same output as grep -l and is simpler.

**Comment by jean-edouard** [comment]
Agreed. I'll build and test this later.

**Comment by jean-edouard** [comment]
This works well, the gap between the end of the partition and the end of the vhd shrinks to about 2MB, which seems perfectly acceptable.
+1

**Comment by jean-edouard** [comment]
This PR is included in http://openxt.ainfosec.com:81/builds/master/ext-dev-284-master/

**Comment by cjp256** [comment]
This calculation rounds down, I'd probably add 1 MB. I believe this works because of the assumptions on the other side?

**Comment by jean-edouard** [comment]
Oh yeah, good catch, this changed so many times that I forgot about that part :)
+1 for +1

**Comment by crogers1** [comment]
Updated.

**Comment by crogers1** [comment]
Are we good to merge?

**Comment by jean-edouard** [comment]
Will merge soon.

**Pull request merged**
