### PR TITLE
OXT-389: implement recommended changes

### PR DESCRIPTION
**Pull request by jean-edouard**
See ticket.

Signed-off-by: Jed <lejosnej@ainfosec.com>

### CODE REVIEW

**Comment by cjp256** [comment]
All in favor of moving to aes-xts-plain64 as upstream cryptsetup has changed that to the default.  Should the other encrypted partitions (log, cores, others?) be switched in the same manner?

**Comment by jean-edouard** [comment]
I thought about that. I figured that we could start simple, and switch the other ones once this PR is tested and merged.

**Comment by rossphilipson** [comment]
+1 this was tested and ready to go. @cjp256 are you cool with @jean-edouard 's approach?

**Comment by cjp256** [comment]
Was just about to ask if there was a build to test this... yeah it LGTM.

**Comment by rossphilipson** [comment]
There may have been a build that @jean-edouard tested. He definitely said it was tested. We can fire up another build if you want to try it out first too.

**Comment by rossphilipson** [comment]
@cjp256 I missed the part about let's merge. I think we all agree. Doing that now.

**Pull request merged**
